### ISSUE TITLE
[melodic migration] Package is not compiling in melodic with new gcc 

### ISSUE THREAD

**Issue by abhishekpadalkar** [b-it-bots/mercury_planner#1]
A syntax change is required in one of the files in downloaded .zip file. We can write a python script to change this line after every time we unzip the file.

**Comment by abhishekpadalkar** [comment]
![image](https://user-images.githubusercontent.com/8361278/49015805-75417000-f184-11e8-9995-ffec96359e41.png)
Second `if` in the highlighted section is the problem. Reference: [https://gcc.gnu.org/gcc-6/changes.html](https://gcc.gnu.org/gcc-6/changes.html) . Search for [-Wmisleading-indentation]

**Comment by sthoduka** [comment]
it's also possible to disable the warning with the CXX flag `-Wno-error=misleading-indentation`

**Comment by abhishekpadalkar** [comment]
![screenshot from 2018-11-26 19-14-53](https://user-images.githubusercontent.com/8361278/49033511-a97e5600-f1af-11e8-9722-05161bf62319.png)
Its not a warning, its an error. So if this applies for the same then its ok.

**Comment by abhishekpadalkar** [comment]
@sthoduka tried your suggestion. Didn't work. Maybe you can try if you have time.

**Comment by sthoduka** [comment]
fixed by #2
